---
title: "eBirds Weekapaug, Washington County, RI"
author: "Vivian Lee"
date: '`r Sys.Date()`'
output: 
  pdf_document: default
  html_document: default
geometry:
  margin=0.7in
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(message = FALSE)
library(rvest)
library(tidyverse)
library(lubridate)
```

## Bird Sightings By Species Over Time  

Data gathered from ebird.org  

Spring Migration (Mar-May)  
Breeding Season (Jun-Jul)  
Fall Migration (Aug-Nov)  
Winter (Dec-Feb)  

```{r ri_ebirds, message=FALSE}

# Function to extract bird sighting data

get_bird_sightings <- function(url) {
  # Scrape the results from the given url from eBirds for a specific region 
  # Args:
  #   url - the url for the eBirds region page
  # Return:
  #   A data frame containing the bird information organized by species code, name, and
  #   total sightings for specified date range, default = all sightings to date
  region_page <- read_html(url)
  
  bird_sightings <- html_node(region_page, 'body') %>%
    html_node(css='#sightingsTable') %>%
    html_node('tbody') %>%
    html_nodes(xpath='//tr[contains(@id, "has-det")]')
    
  species <- bird_sightings %>%
    html_nodes(css='.species-name') %>%
    html_node('a')
  
  species_codes <- species %>%
    html_attr('data-species-code')
  
  species_names <- species %>%
    html_text()
  
  # X connotes 1 or more birds sighted. Replace X with 1 since at least 1 bird was sighted.
  counts <- bird_sightings %>%
    html_node(xpath='td[@headers="c"]') %>%
    html_text() %>%
    map_chr(function(x) ifelse(x=="X", 1, x)) %>%
    as.integer()
    
  # Suppress warnings when NA is assigned to missing dates
  dates <- suppressWarnings(bird_sightings %>%
    html_node(xpath = 'td[@headers="d"]') %>%
    html_text() %>%
    dmy())
  
  # Construct dataframe of bird sighting data, omit records without a name column value
  # as these are sightings without where the bird species was not properly identified
  # and they do not follow a proper naming convention
  tibble(
    code = species_codes,
    name = species_names,
    count = counts,
    date = dates
  ) %>%
    filter(!is.na(date))
}

# rhode_island_df %>%
#   filter(grepl('Warbler', name))

# birds_df %>%
#   group_by(name, code) %>%
#   summarise(
#     count = sum(count, na.rm = TRUE)
#   )

```

Create data tables for bird sightings in Weekapaug, Washington County, and Rhode Island

```{r}
# (weekapaug_df <- get_bird_sightings('https://ebird.org/hotspot/L620475?yr=all&m=&rank=mrec'))
(washington_county_df = get_bird_sightings('https://ebird.org/subnational2/US-RI-009?yr=all&m=&rank=mrec'))
```

```{r birds_for_date_range, message=FALSE}
get_bird_sightings_for_date_range <- function(df, start_date, end_date) {
  # Get bird sightings that occurred within the specified date range for a given dataframe
  # Args:
  #   df - the dataframe to filter
  #   start_date - the start date in YYYY-MM-DD format, inclusive
  #   end_date - the end date in YYYY-MM-DD format, non-inclusive
  # Return:
  #   A data frame containing the bird sightings from the given df, filtered for the
  #   specified date range
  if (missing(start_date) & missing(end_date)) { 
    df 
  }
  else if (missing(start_date)) { 
    df %>% filter(date < as.Date(end_date)) 
  }
  else if (missing(end_date)) { 
    df %>% filter(date >= as.Date(start_date)) 
  }
  else {
    df %>% filter(date >= as.Date(start_date) & date < as.Date(end_date))
  }
}

# Spring Migration (Mar-May)  
# Breeding Season (Jun-Jul)  
# Fall Migration (Aug-Nov)  
# Winter (Dec-Feb)  
# All (Mar-Feb)

get_bird_sightings_for_season_year <- function(df, season, year) {
  # Get bird sightings that occurred for the specified season and year for a given dataframe
  # Args:
  #   df - the dataframe to filter
  #   season - one of ['spring', 'breeding', 'fall', 'winter', 'all']
  #   year - the year to filter for
  # Return:
  #   A data frame containing the bird sightings from the given df, filtered for the
  #   specified season and year
  
  if (!season %in% c("spring", "breeding", "fall", "winter", "all"))
    stop("season arg must be one of ['spring', 'breeding', 'fall', 'winter', 'all']")
  
  if (year < 1970)
    stop("year must be between 1970-present")
  
  start_month <- switch(season, "spring" = 3,"breeding" = 6,"fall" = 8,"winter" = 12, "all" = 3)
  end_month <- switch(season, "spring" = 6, "breeding" = 8, "fall" = 12, "winter" = 3, "all" = 3)
  start_year <- year
  end_year <- ifelse(season %in% c("winter", "all"), year+1, year)
  start_date <- str_c(start_year, start_month, 1, sep="-")
  end_date <- str_c(end_year, end_month, 1, sep="-")
  
  get_bird_sightings_for_date_range(df, start_date, end_date)
}

get_count_per_season_data <- function(df, year) {
  seasons <- c("spring", "breeding", "fall", "winter", "all")
  c(year, unlist(map(seasons, function(x) sum(get_bird_sightings_for_season_year(df, x, year)$count))))
}

# start_year (inclusive) to end_year (inclusive)
get_count_per_season_for_year_range <- function(df, start_year, end_year) {
  years <- start_year:end_year
  year_row_data <- map(years, function(x) get_count_per_season_data(df, x))
  result_df <- data.frame(do.call(rbind, year_row_data))
  colnames(result_df) <- c("year","spring", "breeding", "fall", "winter", "all")
  result_df
}

# get_count_per_season_for_year_range <- function(df, start_year, end_year) {
#   if (start_year > end_year)
#     stop("start_year must come before end year")
#   
#   if (start_year < 1970 | end_year < 1970)
#     stop("given years must be between 1970-present")
#   
#   years <- start_year:end_year
#   data.frame(do.call(rbind, years))
#   data.frame(rbind(map_dfr(years, function(x) get_count_per_season(df, x))))
# }

```

```{r}
# Get bird sighting data for each season in Washington County, RI (2019)

# Change in total bird sightings recorded in the fall season from 2010-2019
get_count_per_season_for_year_range(washington_county_df, 2010, 2019)

```

```{r}
# # Weekapaug bird sightings 2018-present
# get_bird_sightings_for_date_range(weekapaug_df, start_date="2018-01-01")
# 
# # Weekapaug bird sightings 2010-2015
# get_bird_sightings_for_date_range(weekapaug_df, start_date="2010-01-01", end_date="2015-01-01")
# 
# # Weekapaug bird sightings 2019 ordered by frequency
# get_bird_sightings_for_date_range(weekapaug_df, start_date="2019-01-01") %>%
#   arrange(desc(count))
```

